[package]
name = "lumin/plugin-framework"
version = "0.6.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
framework = "lumin/framework@9.0.0"
debugger = "lumin/debugger@0.4.0"
